<?php
/**
 * DefaultApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fareharbor API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * DefaultApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation bookingTour
     *
     * Booking tour
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body body (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\BookingResponse
     */
    public function bookingTour($company_short_name, $availability_id, $body = null)
    {
        list($response) = $this->bookingTourWithHttpInfo($company_short_name, $availability_id, $body);
        return $response;
    }

    /**
     * Operation bookingTourWithHttpInfo
     *
     * Booking tour
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\BookingResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function bookingTourWithHttpInfo($company_short_name, $availability_id, $body = null)
    {
        $returnType = '\Swagger\Client\Model\BookingResponse';
        $request = $this->bookingTourRequest($company_short_name, $availability_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\BookingResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation bookingTourAsync
     *
     * Booking tour
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bookingTourAsync($company_short_name, $availability_id, $body = null)
    {
        return $this->bookingTourAsyncWithHttpInfo($company_short_name, $availability_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation bookingTourAsyncWithHttpInfo
     *
     * Booking tour
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function bookingTourAsyncWithHttpInfo($company_short_name, $availability_id, $body = null)
    {
        $returnType = '\Swagger\Client\Model\BookingResponse';
        $request = $this->bookingTourRequest($company_short_name, $availability_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'bookingTour'
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function bookingTourRequest($company_short_name, $availability_id, $body = null)
    {
        // verify the required parameter 'company_short_name' is set
        if ($company_short_name === null || (is_array($company_short_name) && count($company_short_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_short_name when calling bookingTour'
            );
        }
        // verify the required parameter 'availability_id' is set
        if ($availability_id === null || (is_array($availability_id) && count($availability_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $availability_id when calling bookingTour'
            );
        }

        $resourcePath = '/companies/{company-short-name}/availabilities/{availability-id}/bookings/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($company_short_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company-short-name' . '}',
                ObjectSerializer::toPathValue($company_short_name),
                $resourcePath
            );
        }
        // path params
        if ($availability_id !== null) {
            $resourcePath = str_replace(
                '{' . 'availability-id' . '}',
                ObjectSerializer::toPathValue($availability_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation companiesCompanyShortNameBookingsBookingIdDelete
     *
     * Cancel a booking
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\AvailabilitiesList
     */
    public function companiesCompanyShortNameBookingsBookingIdDelete($company_short_name, $booking_id)
    {
        list($response) = $this->companiesCompanyShortNameBookingsBookingIdDeleteWithHttpInfo($company_short_name, $booking_id);
        return $response;
    }

    /**
     * Operation companiesCompanyShortNameBookingsBookingIdDeleteWithHttpInfo
     *
     * Cancel a booking
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\AvailabilitiesList, HTTP status code, HTTP response headers (array of strings)
     */
    public function companiesCompanyShortNameBookingsBookingIdDeleteWithHttpInfo($company_short_name, $booking_id)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->companiesCompanyShortNameBookingsBookingIdDeleteRequest($company_short_name, $booking_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\AvailabilitiesList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation companiesCompanyShortNameBookingsBookingIdDeleteAsync
     *
     * Cancel a booking
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function companiesCompanyShortNameBookingsBookingIdDeleteAsync($company_short_name, $booking_id)
    {
        return $this->companiesCompanyShortNameBookingsBookingIdDeleteAsyncWithHttpInfo($company_short_name, $booking_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation companiesCompanyShortNameBookingsBookingIdDeleteAsyncWithHttpInfo
     *
     * Cancel a booking
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function companiesCompanyShortNameBookingsBookingIdDeleteAsyncWithHttpInfo($company_short_name, $booking_id)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->companiesCompanyShortNameBookingsBookingIdDeleteRequest($company_short_name, $booking_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'companiesCompanyShortNameBookingsBookingIdDelete'
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function companiesCompanyShortNameBookingsBookingIdDeleteRequest($company_short_name, $booking_id)
    {
        // verify the required parameter 'company_short_name' is set
        if ($company_short_name === null || (is_array($company_short_name) && count($company_short_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_short_name when calling companiesCompanyShortNameBookingsBookingIdDelete'
            );
        }
        // verify the required parameter 'booking_id' is set
        if ($booking_id === null || (is_array($booking_id) && count($booking_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $booking_id when calling companiesCompanyShortNameBookingsBookingIdDelete'
            );
        }

        $resourcePath = '/companies/{company-short-name}/bookings/{booking-id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($company_short_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company-short-name' . '}',
                ObjectSerializer::toPathValue($company_short_name),
                $resourcePath
            );
        }
        // path params
        if ($booking_id !== null) {
            $resourcePath = str_replace(
                '{' . 'booking-id' . '}',
                ObjectSerializer::toPathValue($booking_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getBookingDetail
     *
     * Get booking details
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\AvailabilitiesList
     */
    public function getBookingDetail($company_short_name, $booking_id)
    {
        list($response) = $this->getBookingDetailWithHttpInfo($company_short_name, $booking_id);
        return $response;
    }

    /**
     * Operation getBookingDetailWithHttpInfo
     *
     * Get booking details
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\AvailabilitiesList, HTTP status code, HTTP response headers (array of strings)
     */
    public function getBookingDetailWithHttpInfo($company_short_name, $booking_id)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->getBookingDetailRequest($company_short_name, $booking_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\AvailabilitiesList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getBookingDetailAsync
     *
     * Get booking details
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBookingDetailAsync($company_short_name, $booking_id)
    {
        return $this->getBookingDetailAsyncWithHttpInfo($company_short_name, $booking_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getBookingDetailAsyncWithHttpInfo
     *
     * Get booking details
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getBookingDetailAsyncWithHttpInfo($company_short_name, $booking_id)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->getBookingDetailRequest($company_short_name, $booking_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getBookingDetail'
     *
     * @param  string $company_short_name Company short name (required)
     * @param  string $booking_id Booking id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getBookingDetailRequest($company_short_name, $booking_id)
    {
        // verify the required parameter 'company_short_name' is set
        if ($company_short_name === null || (is_array($company_short_name) && count($company_short_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_short_name when calling getBookingDetail'
            );
        }
        // verify the required parameter 'booking_id' is set
        if ($booking_id === null || (is_array($booking_id) && count($booking_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $booking_id when calling getBookingDetail'
            );
        }

        $resourcePath = '/companies/{company-short-name}/bookings/{booking-id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($company_short_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company-short-name' . '}',
                ObjectSerializer::toPathValue($company_short_name),
                $resourcePath
            );
        }
        // path params
        if ($booking_id !== null) {
            $resourcePath = str_replace(
                '{' . 'booking-id' . '}',
                ObjectSerializer::toPathValue($booking_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCompanies
     *
     * Get companies
     *
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\CompaniesList
     */
    public function getCompanies()
    {
        list($response) = $this->getCompaniesWithHttpInfo();
        return $response;
    }

    /**
     * Operation getCompaniesWithHttpInfo
     *
     * Get companies
     *
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\CompaniesList, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCompaniesWithHttpInfo()
    {
        $returnType = '\Swagger\Client\Model\CompaniesList';
        $request = $this->getCompaniesRequest();

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\CompaniesList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCompaniesAsync
     *
     * Get companies
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompaniesAsync()
    {
        return $this->getCompaniesAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCompaniesAsyncWithHttpInfo
     *
     * Get companies
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompaniesAsyncWithHttpInfo()
    {
        $returnType = '\Swagger\Client\Model\CompaniesList';
        $request = $this->getCompaniesRequest();

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCompanies'
     *
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getCompaniesRequest()
    {

        $resourcePath = '/companies/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getCompanyItems
     *
     * Get company tours
     *
     * @param  string $company_short_name Company short name (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\ToursList
     */
    public function getCompanyItems($company_short_name)
    {
        list($response) = $this->getCompanyItemsWithHttpInfo($company_short_name);
        return $response;
    }

    /**
     * Operation getCompanyItemsWithHttpInfo
     *
     * Get company tours
     *
     * @param  string $company_short_name Company short name (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\ToursList, HTTP status code, HTTP response headers (array of strings)
     */
    public function getCompanyItemsWithHttpInfo($company_short_name)
    {
        $returnType = '\Swagger\Client\Model\ToursList';
        $request = $this->getCompanyItemsRequest($company_short_name);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\ToursList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getCompanyItemsAsync
     *
     * Get company tours
     *
     * @param  string $company_short_name Company short name (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompanyItemsAsync($company_short_name)
    {
        return $this->getCompanyItemsAsyncWithHttpInfo($company_short_name)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getCompanyItemsAsyncWithHttpInfo
     *
     * Get company tours
     *
     * @param  string $company_short_name Company short name (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getCompanyItemsAsyncWithHttpInfo($company_short_name)
    {
        $returnType = '\Swagger\Client\Model\ToursList';
        $request = $this->getCompanyItemsRequest($company_short_name);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getCompanyItems'
     *
     * @param  string $company_short_name Company short name (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getCompanyItemsRequest($company_short_name)
    {
        // verify the required parameter 'company_short_name' is set
        if ($company_short_name === null || (is_array($company_short_name) && count($company_short_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_short_name when calling getCompanyItems'
            );
        }

        $resourcePath = '/companies/{company-short-name}/items/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($company_short_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company-short-name' . '}',
                ObjectSerializer::toPathValue($company_short_name),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getDetailAvailabilityTour
     *
     * Get availability tour
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\AvailabilitiesList
     */
    public function getDetailAvailabilityTour($company_short_name, $availability_id)
    {
        list($response) = $this->getDetailAvailabilityTourWithHttpInfo($company_short_name, $availability_id);
        return $response;
    }

    /**
     * Operation getDetailAvailabilityTourWithHttpInfo
     *
     * Get availability tour
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\AvailabilitiesList, HTTP status code, HTTP response headers (array of strings)
     */
    public function getDetailAvailabilityTourWithHttpInfo($company_short_name, $availability_id)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->getDetailAvailabilityTourRequest($company_short_name, $availability_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\AvailabilitiesList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getDetailAvailabilityTourAsync
     *
     * Get availability tour
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDetailAvailabilityTourAsync($company_short_name, $availability_id)
    {
        return $this->getDetailAvailabilityTourAsyncWithHttpInfo($company_short_name, $availability_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getDetailAvailabilityTourAsyncWithHttpInfo
     *
     * Get availability tour
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getDetailAvailabilityTourAsyncWithHttpInfo($company_short_name, $availability_id)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->getDetailAvailabilityTourRequest($company_short_name, $availability_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getDetailAvailabilityTour'
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getDetailAvailabilityTourRequest($company_short_name, $availability_id)
    {
        // verify the required parameter 'company_short_name' is set
        if ($company_short_name === null || (is_array($company_short_name) && count($company_short_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_short_name when calling getDetailAvailabilityTour'
            );
        }
        // verify the required parameter 'availability_id' is set
        if ($availability_id === null || (is_array($availability_id) && count($availability_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $availability_id when calling getDetailAvailabilityTour'
            );
        }

        $resourcePath = '/companies/{company-short-name}/availabilities/{availability-id}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($company_short_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company-short-name' . '}',
                ObjectSerializer::toPathValue($company_short_name),
                $resourcePath
            );
        }
        // path params
        if ($availability_id !== null) {
            $resourcePath = str_replace(
                '{' . 'availability-id' . '}',
                ObjectSerializer::toPathValue($availability_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getToursByDateRange
     *
     * Get company tours by date range
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $tour_id Tour id (required)
     * @param  string $start_date Date (required)
     * @param  string $end_date Date (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\AvailabilitiesList
     */
    public function getToursByDateRange($company_short_name, $tour_id, $start_date, $end_date)
    {
        list($response) = $this->getToursByDateRangeWithHttpInfo($company_short_name, $tour_id, $start_date, $end_date);
        return $response;
    }

    /**
     * Operation getToursByDateRangeWithHttpInfo
     *
     * Get company tours by date range
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $tour_id Tour id (required)
     * @param  string $start_date Date (required)
     * @param  string $end_date Date (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\AvailabilitiesList, HTTP status code, HTTP response headers (array of strings)
     */
    public function getToursByDateRangeWithHttpInfo($company_short_name, $tour_id, $start_date, $end_date)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->getToursByDateRangeRequest($company_short_name, $tour_id, $start_date, $end_date);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\AvailabilitiesList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getToursByDateRangeAsync
     *
     * Get company tours by date range
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $tour_id Tour id (required)
     * @param  string $start_date Date (required)
     * @param  string $end_date Date (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getToursByDateRangeAsync($company_short_name, $tour_id, $start_date, $end_date)
    {
        return $this->getToursByDateRangeAsyncWithHttpInfo($company_short_name, $tour_id, $start_date, $end_date)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getToursByDateRangeAsyncWithHttpInfo
     *
     * Get company tours by date range
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $tour_id Tour id (required)
     * @param  string $start_date Date (required)
     * @param  string $end_date Date (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getToursByDateRangeAsyncWithHttpInfo($company_short_name, $tour_id, $start_date, $end_date)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->getToursByDateRangeRequest($company_short_name, $tour_id, $start_date, $end_date);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getToursByDateRange'
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $tour_id Tour id (required)
     * @param  string $start_date Date (required)
     * @param  string $end_date Date (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getToursByDateRangeRequest($company_short_name, $tour_id, $start_date, $end_date)
    {
        // verify the required parameter 'company_short_name' is set
        if ($company_short_name === null || (is_array($company_short_name) && count($company_short_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_short_name when calling getToursByDateRange'
            );
        }
        // verify the required parameter 'tour_id' is set
        if ($tour_id === null || (is_array($tour_id) && count($tour_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tour_id when calling getToursByDateRange'
            );
        }
        // verify the required parameter 'start_date' is set
        if ($start_date === null || (is_array($start_date) && count($start_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $start_date when calling getToursByDateRange'
            );
        }
        // verify the required parameter 'end_date' is set
        if ($end_date === null || (is_array($end_date) && count($end_date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $end_date when calling getToursByDateRange'
            );
        }

        $resourcePath = '/companies/{company-short-name}/items/{tour-id}/minimal/availabilities/date-range/{start-date}/{end-date}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($company_short_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company-short-name' . '}',
                ObjectSerializer::toPathValue($company_short_name),
                $resourcePath
            );
        }
        // path params
        if ($tour_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tour-id' . '}',
                ObjectSerializer::toPathValue($tour_id),
                $resourcePath
            );
        }
        // path params
        if ($start_date !== null) {
            $resourcePath = str_replace(
                '{' . 'start-date' . '}',
                ObjectSerializer::toPathValue($start_date),
                $resourcePath
            );
        }
        // path params
        if ($end_date !== null) {
            $resourcePath = str_replace(
                '{' . 'end-date' . '}',
                ObjectSerializer::toPathValue($end_date),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getToursOnDate
     *
     * Get tours for date
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $tour_id Tour id (required)
     * @param  string $date Date (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\AvailabilitiesList
     */
    public function getToursOnDate($company_short_name, $tour_id, $date)
    {
        list($response) = $this->getToursOnDateWithHttpInfo($company_short_name, $tour_id, $date);
        return $response;
    }

    /**
     * Operation getToursOnDateWithHttpInfo
     *
     * Get tours for date
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $tour_id Tour id (required)
     * @param  string $date Date (required)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\AvailabilitiesList, HTTP status code, HTTP response headers (array of strings)
     */
    public function getToursOnDateWithHttpInfo($company_short_name, $tour_id, $date)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->getToursOnDateRequest($company_short_name, $tour_id, $date);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\AvailabilitiesList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getToursOnDateAsync
     *
     * Get tours for date
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $tour_id Tour id (required)
     * @param  string $date Date (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getToursOnDateAsync($company_short_name, $tour_id, $date)
    {
        return $this->getToursOnDateAsyncWithHttpInfo($company_short_name, $tour_id, $date)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getToursOnDateAsyncWithHttpInfo
     *
     * Get tours for date
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $tour_id Tour id (required)
     * @param  string $date Date (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getToursOnDateAsyncWithHttpInfo($company_short_name, $tour_id, $date)
    {
        $returnType = '\Swagger\Client\Model\AvailabilitiesList';
        $request = $this->getToursOnDateRequest($company_short_name, $tour_id, $date);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getToursOnDate'
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $tour_id Tour id (required)
     * @param  string $date Date (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getToursOnDateRequest($company_short_name, $tour_id, $date)
    {
        // verify the required parameter 'company_short_name' is set
        if ($company_short_name === null || (is_array($company_short_name) && count($company_short_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_short_name when calling getToursOnDate'
            );
        }
        // verify the required parameter 'tour_id' is set
        if ($tour_id === null || (is_array($tour_id) && count($tour_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tour_id when calling getToursOnDate'
            );
        }
        // verify the required parameter 'date' is set
        if ($date === null || (is_array($date) && count($date) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $date when calling getToursOnDate'
            );
        }

        $resourcePath = '/companies/{company-short-name}/items/{tour-id}/minimal/availabilities/date/{date}/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($company_short_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company-short-name' . '}',
                ObjectSerializer::toPathValue($company_short_name),
                $resourcePath
            );
        }
        // path params
        if ($tour_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tour-id' . '}',
                ObjectSerializer::toPathValue($tour_id),
                $resourcePath
            );
        }
        // path params
        if ($date !== null) {
            $resourcePath = str_replace(
                '{' . 'date' . '}',
                ObjectSerializer::toPathValue($date),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation validateBookingTour
     *
     * Validate bookings
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body body (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Swagger\Client\Model\BookingValidateResponse
     */
    public function validateBookingTour($company_short_name, $availability_id, $body = null)
    {
        list($response) = $this->validateBookingTourWithHttpInfo($company_short_name, $availability_id, $body);
        return $response;
    }

    /**
     * Operation validateBookingTourWithHttpInfo
     *
     * Validate bookings
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \Swagger\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Swagger\Client\Model\BookingValidateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function validateBookingTourWithHttpInfo($company_short_name, $availability_id, $body = null)
    {
        $returnType = '\Swagger\Client\Model\BookingValidateResponse';
        $request = $this->validateBookingTourRequest($company_short_name, $availability_id, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if (!in_array($returnType, ['string','integer','bool'])) {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Swagger\Client\Model\BookingValidateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation validateBookingTourAsync
     *
     * Validate bookings
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateBookingTourAsync($company_short_name, $availability_id, $body = null)
    {
        return $this->validateBookingTourAsyncWithHttpInfo($company_short_name, $availability_id, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation validateBookingTourAsyncWithHttpInfo
     *
     * Validate bookings
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function validateBookingTourAsyncWithHttpInfo($company_short_name, $availability_id, $body = null)
    {
        $returnType = '\Swagger\Client\Model\BookingValidateResponse';
        $request = $this->validateBookingTourRequest($company_short_name, $availability_id, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'validateBookingTour'
     *
     * @param  string $company_short_name Company short name (required)
     * @param  int $availability_id Availability id (required)
     * @param  \Swagger\Client\Model\Booking $body (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function validateBookingTourRequest($company_short_name, $availability_id, $body = null)
    {
        // verify the required parameter 'company_short_name' is set
        if ($company_short_name === null || (is_array($company_short_name) && count($company_short_name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $company_short_name when calling validateBookingTour'
            );
        }
        // verify the required parameter 'availability_id' is set
        if ($availability_id === null || (is_array($availability_id) && count($availability_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $availability_id when calling validateBookingTour'
            );
        }

        $resourcePath = '/companies/{company-short-name}/availabilities/{availability-id}/bookings/validate/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($company_short_name !== null) {
            $resourcePath = str_replace(
                '{' . 'company-short-name' . '}',
                ObjectSerializer::toPathValue($company_short_name),
                $resourcePath
            );
        }
        // path params
        if ($availability_id !== null) {
            $resourcePath = str_replace(
                '{' . 'availability-id' . '}',
                ObjectSerializer::toPathValue($availability_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['text/plain']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['text/plain'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-App');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-App'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-FareHarbor-API-User');
        if ($apiKey !== null) {
            $headers['X-FareHarbor-API-User'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
