<?php
/**
 * Customer
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fareharbor API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Customer Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Customer implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Customer';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'checkin_url' => 'string',
'checkin_status' => '\Swagger\Client\Model\CustomerCheckInStatus',
'customer_type_rate' => '\Swagger\Client\Model\CustomerTypeRateResponse'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'checkin_url' => null,
'checkin_status' => null,
'customer_type_rate' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'checkin_url' => 'checkin_url',
'checkin_status' => 'checkin_status',
'customer_type_rate' => 'customer_type_rate'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'checkin_url' => 'setCheckinUrl',
'checkin_status' => 'setCheckinStatus',
'customer_type_rate' => 'setCustomerTypeRate'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'checkin_url' => 'getCheckinUrl',
'checkin_status' => 'getCheckinStatus',
'customer_type_rate' => 'getCustomerTypeRate'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['checkin_url'] = isset($data['checkin_url']) ? $data['checkin_url'] : null;
        $this->container['checkin_status'] = isset($data['checkin_status']) ? $data['checkin_status'] : null;
        $this->container['customer_type_rate'] = isset($data['customer_type_rate']) ? $data['customer_type_rate'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets checkin_url
     *
     * @return string
     */
    public function getCheckinUrl()
    {
        return $this->container['checkin_url'];
    }

    /**
     * Sets checkin_url
     *
     * @param string $checkin_url checkin_url
     *
     * @return $this
     */
    public function setCheckinUrl($checkin_url)
    {
        $this->container['checkin_url'] = $checkin_url;

        return $this;
    }

    /**
     * Gets checkin_status
     *
     * @return \Swagger\Client\Model\CustomerCheckInStatus
     */
    public function getCheckinStatus()
    {
        return $this->container['checkin_status'];
    }

    /**
     * Sets checkin_status
     *
     * @param \Swagger\Client\Model\CustomerCheckInStatus $checkin_status checkin_status
     *
     * @return $this
     */
    public function setCheckinStatus($checkin_status)
    {
        $this->container['checkin_status'] = $checkin_status;

        return $this;
    }

    /**
     * Gets customer_type_rate
     *
     * @return \Swagger\Client\Model\CustomerTypeRateResponse
     */
    public function getCustomerTypeRate()
    {
        return $this->container['customer_type_rate'];
    }

    /**
     * Sets customer_type_rate
     *
     * @param \Swagger\Client\Model\CustomerTypeRateResponse $customer_type_rate customer_type_rate
     *
     * @return $this
     */
    public function setCustomerTypeRate($customer_type_rate)
    {
        $this->container['customer_type_rate'] = $customer_type_rate;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
