<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fareharbor API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for companiesCompanyShortNameAvailabilitiesAvailabilityIdBookingsPost
     *
     * booking.
     *
     */
    public function testCompaniesCompanyShortNameAvailabilitiesAvailabilityIdBookingsPost()
    {
    }

    /**
     * Test case for companiesCompanyShortNameAvailabilitiesAvailabilityIdBookingsValidatePost
     *
     * check bookings.
     *
     */
    public function testCompaniesCompanyShortNameAvailabilitiesAvailabilityIdBookingsValidatePost()
    {
    }

    /**
     * Test case for companiesCompanyShortNameAvailabilitiesAvailabilityIdGet
     *
     * get availability tour.
     *
     */
    public function testCompaniesCompanyShortNameAvailabilitiesAvailabilityIdGet()
    {
    }

    /**
     * Test case for companiesCompanyShortNameBookingsBookingIdDelete
     *
     * get availability tour.
     *
     */
    public function testCompaniesCompanyShortNameBookingsBookingIdDelete()
    {
    }

    /**
     * Test case for companiesCompanyShortNameBookingsBookingIdGet
     *
     * get availability tour.
     *
     */
    public function testCompaniesCompanyShortNameBookingsBookingIdGet()
    {
    }

    /**
     * Test case for companiesCompanyShortNameItemsGet
     *
     * get company tours.
     *
     */
    public function testCompaniesCompanyShortNameItemsGet()
    {
    }

    /**
     * Test case for companiesCompanyShortNameItemsTourIdMinimalAvailabilitiesDateDateGet
     *
     * get company tours.
     *
     */
    public function testCompaniesCompanyShortNameItemsTourIdMinimalAvailabilitiesDateDateGet()
    {
    }

    /**
     * Test case for companiesCompanyShortNameItemsTourIdMinimalAvailabilitiesDateRangeStartDateEndDateGet
     *
     * get company tours.
     *
     */
    public function testCompaniesCompanyShortNameItemsTourIdMinimalAvailabilitiesDateRangeStartDateEndDateGet()
    {
    }

    /**
     * Test case for companiesGet
     *
     * Get companies.
     *
     */
    public function testCompaniesGet()
    {
    }
}
