<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * fareharbor API
 *
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.20
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for bookingTour
     *
     * Booking tour.
     *
     */
    public function testBookingTour()
    {
    }

    /**
     * Test case for deleteBooking
     *
     * Cancel a booking.
     *
     */
    public function testDeleteBooking()
    {
    }

    /**
     * Test case for getBookingDetail
     *
     * Get booking details.
     *
     */
    public function testGetBookingDetail()
    {
    }

    /**
     * Test case for getCompanies
     *
     * Get companies.
     *
     */
    public function testGetCompanies()
    {
    }

    /**
     * Test case for getCompanyItems
     *
     * Get company tours.
     *
     */
    public function testGetCompanyItems()
    {
    }

    /**
     * Test case for getDetailAvailabilityTour
     *
     * Get availability tour.
     *
     */
    public function testGetDetailAvailabilityTour()
    {
    }

    /**
     * Test case for getToursByDateRange
     *
     * Get company tours by date range.
     *
     */
    public function testGetToursByDateRange()
    {
    }

    /**
     * Test case for getToursOnDate
     *
     * Get tours for date.
     *
     */
    public function testGetToursOnDate()
    {
    }

    /**
     * Test case for validateBookingTour
     *
     * Validate bookings.
     *
     */
    public function testValidateBookingTour()
    {
    }
}
